[phases.setup]
aptPkgs = ["ffmpeg", "libcairo2-dev", "libpango1.0-dev", "libpangocairo-1.0-0", "pkg-config", "fonts-dejavu-core", "python3-dev", "gcc", "libffi-dev"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "fastapi run main.py --host 0.0.0.0 --port $PORT"
